# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fdbe7ac6c759064ff099b0e4b290514a"
name = "Sync Order-Inventory"
handle = "sync-order-inventory"
application_url = "https://rewards-deferred-tutorials-paths.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nextgen-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://rewards-deferred-tutorials-paths.trycloudflare.com/auth/callback",
  "https://rewards-deferred-tutorials-paths.trycloudflare.com/auth/shopify/callback",
  "https://rewards-deferred-tutorials-paths.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
