# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fdbe7ac6c759064ff099b0e4b290514a"
name = "Sync Order-Inventory"
handle = "sync-order-inventory"
application_url = "https://rendered-mpeg-numbers-oxygen.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nextgen-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,write_assigned_fulfillment_orders,write_inventory,write_locations,write_merchant_managed_fulfillment_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://rendered-mpeg-numbers-oxygen.trycloudflare.com/auth/callback",
  "https://rendered-mpeg-numbers-oxygen.trycloudflare.com/auth/shopify/callback",
  "https://rendered-mpeg-numbers-oxygen.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://rendered-mpeg-numbers-oxygen.trycloudflare.com"
subpath = "sync-order-inventory"
prefix = "apps"

[pos]
embedded = false
